// hq — a cmux custom sidebar.
//
// Colours and icons are automatic: every repository gets a stable colour derived
// from its directory name, so this works on any machine with no configuration.
// To pin a specific colour or icon, add a line inside the override functions
// below. bin/scan-projects.sh can generate those lines for you.

let palette = ["#FF7A45", "#7FD98A", "#4FC3D9", "#C79BF0", "#F2C55C",
               "#7FB4FF", "#FF8A8A", "#6FDCB4", "#D4A574", "#E88FC0"]

let spinner = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]

// >>> project overrides — generated by bin/scan-projects.sh, safe to hand-edit
func colorOverride(_ dir: String) -> String {
    // if dir.contains("my-repo") { return "#FF7A45" }
    return ""
}

func iconOverride(_ dir: String) -> String {
    // if dir.contains("my-repo") { return "hammer.fill" }
    return ""
}
// <<< project overrides

func hue(_ dir: String) -> String {
    let pinned = colorOverride(dir)
    if pinned != "" { return pinned }
    let name = dir.split(separator: "/").last
    return palette[name.count % 10]
}

func icon(_ dir: String) -> String {
    let pinned = iconOverride(dir)
    if pinned != "" { return pinned }
    return "folder.fill"
}

VStack(alignment: .leading, spacing: 0) {

    HStack(spacing: 6) {
        Image(systemName: "square.stack.3d.up.fill")
            .font(.system(size: 13))
            .foregroundColor("#E4572E")
        Text("HQ")
            .font(.system(size: 12))
            .fontWeight(.semibold)
            .textCase(.uppercase)
            .foregroundColor("#A7B2BF")
        Spacer()
        Text(clock.time)
            .font(.system(size: 12))
            .monospacedDigit()
            .foregroundColor("#7A8695")
    }
    .padding(10)

    Divider()

    Reorderable(workspaces.prefix(24), move: "workspace.reorder") { w in
        VStack(alignment: .leading, spacing: 0) {

            Button(action: { cmux("workspace.select", workspace_id: w.id) }) {
                HStack(spacing: 10) {

                    if let c = w.color {
                        RoundedRectangle(cornerRadius: 3)
                            .fill(c)
                            .frame(width: 9, height: 46)
                    } else {
                        RoundedRectangle(cornerRadius: 3)
                            .fill(hue(w.directory))
                            .frame(width: 9, height: 46)
                    }

                    if let c = w.color {
                        Image(systemName: icon(w.directory))
                            .font(.system(size: 15))
                            .foregroundColor(c)
                            .frame(width: 20)
                    } else {
                        Image(systemName: icon(w.directory))
                            .font(.system(size: 15))
                            .foregroundColor(hue(w.directory))
                            .frame(width: 20)
                    }

                    VStack(alignment: .leading, spacing: 5) {

                        HStack(spacing: 6) {
                            Text(w.title)
                                .font(.system(size: 15))
                                .fontWeight(.semibold)
                                .lineLimit(1)
                                .truncationMode(.tail)
                                .foregroundColor(w.selected ? "#F5F1EA" : "#C2CBD5")
                            Spacer()
                            if let la = w.latestAt {
                                if clock.epoch - la < 45 {
                                    Text(spinner[clock.second % 10])
                                        .font(.system(size: 13))
                                        .fontWeight(.bold)
                                        .foregroundColor(hue(w.directory))
                                }
                            }
                            if let p = w.progress {
                                Text(spinner[clock.second % 10])
                                    .font(.system(size: 13))
                                    .fontWeight(.bold)
                                    .foregroundColor("#E8B04B")
                            }
                            if w.unread > 0 {
                                Text("\(w.unread)")
                                    .font(.system(size: 12))
                                    .fontWeight(.bold)
                                    .monospacedDigit()
                                    .foregroundColor("#0E1319")
                                    .padding(4)
                                    .background("#E4572E")
                                    .clipShape(Capsule())
                            }
                        }

                        HStack(spacing: 7) {
                            if let d = w.dirty {
                                Circle()
                                    .fill(d ? "#E8B04B" : "#5A9E6F")
                                    .frame(width: 7, height: 7)
                            }
                            if let b = w.branch {
                                Text(b)
                                    .font(.system(size: 12))
                                    .fontWeight(.medium)
                                    .lineLimit(1)
                                    .truncationMode(.tail)
                                    .foregroundColor("#93A0AE")
                            }
                            if let pr = w.pr {
                                Text("#\(pr.number)")
                                    .font(.system(size: 12))
                                    .fontWeight(.medium)
                                    .monospacedDigit()
                                    .foregroundColor(pr.status == "merged" ? "#A98BD4" : (pr.status == "closed" ? "#C9584B" : "#5FB88E"))
                            }
                            if w.portCount > 0 {
                                Image(systemName: "bolt.horizontal.fill")
                                    .font(.system(size: 10))
                                    .foregroundColor("#3E9BAD")
                                Text("\(w.portCount)")
                                    .font(.system(size: 12))
                                    .fontWeight(.medium)
                                    .monospacedDigit()
                                    .foregroundColor("#3E9BAD")
                            }
                            Spacer()
                        }

                        if let p = w.progress {
                            ProgressView(value: p.value)
                                .tint("#E4572E")
                                .frame(height: 3)
                        }
                    }
                }
                .padding(10)
                .background {
                    ZStack {
                        RoundedRectangle(cornerRadius: 8)
                            .fill(w.selected ? "#1B2531" : "#131A22")
                        if let c = w.color {
                            RoundedRectangle(cornerRadius: 8)
                                .fill(c)
                                .opacity(w.selected ? 0.14 : 0.07)
                        } else {
                            RoundedRectangle(cornerRadius: 8)
                                .fill(hue(w.directory))
                                .opacity(w.selected ? 0.14 : 0.07)
                        }
                    }
                }
                .cornerRadius(8)
                .overlay {
                    if let c = w.color {
                        RoundedRectangle(cornerRadius: 8)
                            .stroke(w.selected ? "#E4572E" : c, lineWidth: w.selected ? 2 : 1)
                            .opacity(w.selected ? 1.0 : 0.8)
                    } else {
                        RoundedRectangle(cornerRadius: 8)
                            .stroke(w.selected ? "#E4572E" : hue(w.directory), lineWidth: w.selected ? 2 : 1)
                            .opacity(w.selected ? 1.0 : 0.8)
                    }
                }
                .contextMenu {
                    Text("Rename with Shift-Cmd-R")
                    Divider()
                    Button("Pin") { cmux("workspace.action", action: "pin", workspace_id: w.id) }
                    Button("Unpin") { cmux("workspace.action", action: "unpin", workspace_id: w.id) }
                    Button("Mark Read") { cmux("workspace.action", action: "mark-read", workspace_id: w.id) }
                    Button("Mark Unread") { cmux("workspace.action", action: "mark-unread", workspace_id: w.id) }
                    Divider()
                    Divider()
                    Menu("Color") {
                        Button("Blaze") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#FF7A45") }
                        Button("Ember") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#FF8A8A") }
                        Button("Gold") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#F2C55C") }
                        Button("Sand") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#D4A574") }
                        Button("Moss") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#7FD98A") }
                        Button("Mint") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#6FDCB4") }
                        Button("Tide") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#4FC3D9") }
                        Button("Sky") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#7FB4FF") }
                        Button("Violet") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#C79BF0") }
                        Button("Rose") { cmux("workspace.action", action: "set-color", workspace_id: w.id, color: "#E88FC0") }
                        Divider()
                        Button("Clear Color") { cmux("workspace.action", action: "clear-color", workspace_id: w.id) }
                    }
                    Divider()
                    Button("Move Up") { cmux("workspace.action", action: "move-up", workspace_id: w.id) }
                    Button("Move Down") { cmux("workspace.action", action: "move-down", workspace_id: w.id) }
                    Button("Move to Top") { cmux("workspace.action", action: "move-top", workspace_id: w.id) }
                }
            }

            if w.selected {
                VStack(alignment: .leading, spacing: 2) {
                    ForEach(w.tabs.prefix(8)) { t in
                        Button(action: { cmux("surface.focus", surface_id: t.id) }) {
                            HStack(spacing: 7) {
                                Circle()
                                    .fill(t.focused ? "#E4572E" : "#2A3340")
                                    .frame(width: 6, height: 6)
                                Text(t.title)
                                    .font(.system(size: 13))
                                    .fontWeight(t.focused ? .medium : .regular)
                                    .lineLimit(1)
                                    .truncationMode(.tail)
                                    .foregroundColor(t.focused ? "#DCD5C8" : "#8A96A4")
                                Spacer()
                            }
                            .padding(5)
                        }
                    }
                }
                .padding(8)
            }
        }
        .padding(6)
    }

    Spacer()

    Divider()

    HStack(spacing: 6) {
        Text("\(workspaceCount)")
            .font(.system(size: 13))
            .fontWeight(.semibold)
            .monospacedDigit()
            .foregroundColor("#A7B2BF")
        Text("workspaces")
            .font(.system(size: 12))
            .foregroundColor("#7A8695")
        Spacer()
        if unreadTotal > 0 {
            Circle()
                .fill("#E4572E")
                .frame(width: 7, height: 7)
            Text("\(unreadTotal)")
                .font(.system(size: 13))
                .fontWeight(.semibold)
                .monospacedDigit()
                .foregroundColor("#E4572E")
        }
    }
    .padding(10)
}
